version: '3'
services:
    db:
        hostname: mysql
        restart: always
        image: mysql:8.0.26
        command: --default-authentication-plugin=mysql_native_password
        expose:
            - 3306
        environment:
        MYSQL_ROOT_PASSWORD: '123456'
        MYSQL_DATABASE: 'scheduleapp'
        MYSQL_USER: 'user'
        MYSQL_PASS: '123456'
